"""GIN index test2

Revision ID: 0aa16834c563
Revises: 0f2730f54bea
Create Date: 2023-11-16 22:14:40.008487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from models.project import Project

# revision identifiers, used by Alembic.
revision: str = "0aa16834c563"
down_revision: Union[str, None] = "0f2730f54bea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        Project.index.name,
        Project.index.table.name,
        Project.index.expressions,
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"columns": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "projects_name_description_idx",
        table_name="projects",
        postgresql_using="gin",
        postgresql_ops={"columns": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
