"""Add some valuable fields

Revision ID: 21d9a8f71690
Revises: 41536de281a5
Create Date: 2023-11-13 22:20:03.706064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d9a8f71690'
down_revision: Union[str, None] = '41536de281a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('workers', sa.Column('salary', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'salary')
    op.drop_column('projects', 'description')
    op.drop_column('orders', 'description')
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###
