"""JSONB gin index test

Revision ID: 2c968ba0c9ee
Revises: 3614cc5f29ff
Create Date: 2023-11-20 12:07:55.496175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from models.project import Project
from models.worker import Worker

# revision identifiers, used by Alembic.
revision: str = "2c968ba0c9ee"
down_revision: Union[str, None] = "3614cc5f29ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workers",
        sa.Column(
            "details",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=False,
        ),
    )
    op.create_index(
        Worker.index.name,
        Worker.index.table.name,
        Worker.index.expressions,
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"json_details": "jsonb_path_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "workers_details_idx",
        table_name="workers",
        postgresql_using="gin",
        postgresql_ops={"details": "gin_trgm_ops"},
    )
    op.drop_column("workers", "details")
    # ### end Alembic commands ###
