"""Test 1

Revision ID: 326a602e1f4d
Revises: 3e1d6f3b5c60
Create Date: 2023-11-13 21:55:08.164026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326a602e1f4d'
down_revision: Union[str, None] = '3e1d6f3b5c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
