"""Created indexes

Revision ID: 3614cc5f29ff
Revises: 0b58d2367276
Create Date: 2023-11-14 17:43:36.087687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3614cc5f29ff'
down_revision: Union[str, None] = '0b58d2367276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_name'), 'orders', ['name'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_workers_full_name'), 'workers', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_full_name'), table_name='workers')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_orders_name'), table_name='orders')
    # ### end Alembic commands ###
