"""Create a baseline migrations

Revision ID: 3e1d6f3b5c60
Revises: 
Create Date: 2023-11-13 21:02:50.382630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e1d6f3b5c60"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column(
            "cipher",
            sa.INTEGER(),
            server_default=sa.text("nextval('projects_cipher_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("complexity_level", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("cipher", name="projects_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "workers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "full_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("post", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="workers_pkey"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("deadline_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("real_end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("complexity_level", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("worker_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.cipher"], name="fk_projects"
        ),
        sa.ForeignKeyConstraint(["worker_id"], ["workers.id"], name="fk_workers"),
        sa.PrimaryKeyConstraint("id", name="orders_pkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("workers")
    op.drop_table("projects")
    # ### end Alembic commands ###
