"""Test 3

Revision ID: 41536de281a5
Revises: a66701516f60
Create Date: 2023-11-13 22:00:13.551595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41536de281a5'
down_revision: Union[str, None] = 'a66701516f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
