"""Test migration

Revision ID: a3deb357d657
Revises: 2c968ba0c9ee
Create Date: 2023-12-08 21:56:56.617196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from models.project import Project

# revision identifiers, used by Alembic.
revision: str = "a3deb357d657"
down_revision: Union[str, None] = "2c968ba0c9ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_projects_name", table_name="projects")
    op.create_index(
        Project.index.name,
        Project.index.table.name,
        Project.index.expressions,
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"columns": "gin_trgm_ops"},
    )
    op.drop_index("ix_workers_full_name", table_name="workers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_workers_full_name", "workers", ["full_name"], unique=False)
    op.drop_index(
        "projects_name_description_idx",
        table_name="projects",
        postgresql_using="gin",
        postgresql_ops={"columns": "gin_trgm_ops"},
    )
    op.create_index("ix_projects_name", "projects", ["name"], unique=False)
    # ### end Alembic commands ###
